pipeline {
agent any

environment {
    IMAGE_NAME = "saikiran1605/devops-website"
}

stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Build Docker Image') {
        steps {
            sh """
            docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ./project-24
            docker tag ${IMAGE_NAME}:${BUILD_NUMBER} ${IMAGE_NAME}:latest
            """
        }
    }

    stage('Docker Login') {
        steps {
            withCredentials([
                usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )
            ]) {
                sh """
                echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin
                """
            }
        }
    }

    stage('Push Image') {
        steps {
            sh """
            docker push ${IMAGE_NAME}:${BUILD_NUMBER}
            docker push ${IMAGE_NAME}:latest
            """
        }
    }

    stage('Deploy To Kubernetes') {
        steps {
            sh """
            kubectl set image deployment/website-deployment website=${IMAGE_NAME}:${BUILD_NUMBER}
            kubectl rollout status deployment/website-deployment
            """
        }
    }
}

post {
    success {
        echo 'Deployment Successful!'
    }

    failure {
        echo 'Pipeline Failed!'
    }
}

}
