pipeline {
    agent any

    environment {
        IMAGE_NAME = "saikiran1605/devops-website"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                dir('project-16') {
                    sh 'docker build -t $IMAGE_NAME:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                docker push $IMAGE_NAME:${BUILD_NUMBER}
                docker tag $IMAGE_NAME:${BUILD_NUMBER} $IMAGE_NAME:latest
                docker push $IMAGE_NAME:latest
                '''
            }
        }
	stage('Deploy Website') {
 	   steps {
        	sh '''
       		 docker stop website || true
       		 docker rm website || true

       		 docker pull $IMAGE_NAME:latest

       		 docker run -d -p 80:80 \
        	--name website \
        	$IMAGE_NAME:latest
        	'''
    		}
	}
    }
}
