pipeline {
    agent any

    environment {
        IMAGE_NAME = "saikiran1605/devops-website"
        NEXUS_URL = "http://localhost:8081/repository/devops-artifacts"
    }

    stages {

        stage('SonarQube Analysis') {
            steps {
                dir('project-16') {
                    script {
                        def scannerHome = tool 'SonarScanner'

                        withSonarQubeEnv('SonarQube') {
                            sh "${scannerHome}/bin/sonar-scanner"
                        }
                    }
                }
            }
        }

        stage('Create Artifact') {
            steps {
                sh '''
                tar -czvf project-16-${BUILD_NUMBER}.tar.gz project-16
                '''
            }
        }

        stage('Upload Artifact to Nexus') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'nexus-creds',
                        usernameVariable: 'NEXUS_USER',
                        passwordVariable: 'NEXUS_PASS'
                    )
                ]) {
                    sh '''
                    curl -v -u $NEXUS_USER:$NEXUS_PASS \
                    --upload-file project-16-${BUILD_NUMBER}.tar.gz \
                    $NEXUS_URL/project-16-${BUILD_NUMBER}.tar.gz
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('project-16') {
                    sh '''
                    docker build -t $IMAGE_NAME:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                docker push $IMAGE_NAME:${BUILD_NUMBER}

                docker tag $IMAGE_NAME:${BUILD_NUMBER} $IMAGE_NAME:latest

                docker push $IMAGE_NAME:latest
                '''
            }
        }

        stage('Deploy Website') {
            steps {
                sh '''
                docker stop website || true
                docker rm website || true

                docker pull $IMAGE_NAME:latest

                docker run -d \
                --name website \
                -p 80:80 \
                $IMAGE_NAME:latest
                '''
            }
        }
    }
}
